#!/bin/bash
# This hook is sourced before this virtualenv is deactivated.
unset DJANGO_SETTINGS_MODULE
unset SECRET_KEY
unset DB_NAME
unset DB_USER
unset DB_PASSWORD
unset DB_HOST
unset DB_PORT
unset LANGUAGE
unset NORECAPTCHA_SITE_KEY
unset NORECAPTCHA_SECRET_KEY